title: Hyeonseob Nam
url: "https://hyeonseobnam.github.io"
baseurl: ""

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?user=X9BkR3MAAAAJ/"
