title: Hyeonseob Nam
url: "https://hyeonseobnam.github.io"
baseurl: ""
email: "hsnam [at] lunit [dot] io"

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Google Scholar"
   link: "https://scholar.google.co.kr/citations?user=X9BkR3MAAAAJ"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/hyeonseob-nam"
 - name: "GitHub"
   link: "https://github.com/HyeonseobNam"
